app.name=My app
app.description=Welcome to ${app.name}

my.greeting= Greetings, Microservice Spring Config specfic configuration. Update.
my.list.values=One, Two, Three, Four     
management.endpoints.web.exposure.include= "*"
