app:
    name: My app
    description: Welcome to ${app.name}

my:
    greeting: Geetings, Microservice Spring Config specfic configuration. 
    list:
         values: One, Two, Three, Four     
